### ISSUE TITLE
App crashes on quick stop-start action

### ISSUE THREAD

**Issue by hakaishi** [celzero/docs#8]
Android: 13
App versions tested: 053i, 053j
Phone: Google Pixel 4a (5G)

Taken actions to reproduce:
1. Open app
2. tap stop
3. tap start
4. crash

Afterwards the app pushes a message that it was disabled.

Retrying the above will cause the system to inform me about repeated closing down of the app.

It might be a different issue, but since the upgrade to Android 13 (using app versions 053i/053j) tapping on "start" takes a long time (about 20 or 30 seconds).

Best regards,
Hakaishi

**Comment by ignoramous** [comment]
Dup: https://github.com/celzero/rethink-app/issues/512

Fixed it in `v053k` (released in Oct, 2022)

For the next time, pls report app issues here instead https://github.com/celzero/rethink-app/issues :)
